version: "3.0"
services:
  server:
    image: node:14
    ports:
      - 81:80
    volumes:
      - ./src:/app
    working_dir: /app
    entrypoint: ["yarn", "nodemon", "index.js"]

  redis:
    image: redis
    volumes:
      - ./data:/data
