apiVersion: v1
kind: Service
metadata:
  name: redirection
spec:
  type: ExternalName
  externalName: 172.30.1.200
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: redirection
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`redire.ction.link`)||Host(`a.ction.link`)
      services:
        - kind: Service
          name: redirection
          passHostHeader: true
          port: 81
      middlewares:
        - name: redirect-https
  tls: {}
